name: battleship
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies:
  http: ^0.13.4
  textwrap: ^1.1.0
  tint: ^2.0.0
